import 'package:play_books/data/vos/book_search_result.dart';
import 'package:play_books/data/vos/book_vo.dart';
import 'package:play_books/data/vos/books_list_vo.dart';
import 'package:play_books/data/vos/shelf_vo.dart';

List<BooksListVO> getEbooksListMock() {
  return [
    BooksListVO(
        'Combined Print and E-Book Fiction',
        'combined-print-and-e-book-fiction',
        'Combined Print & E-Book Fiction',
        [BookVO(
          'Amor Towles',
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          'THE LINCOLN HIGHWAY',
          null,
          null,
          null,
        )]),
    BooksListVO(
        'Hardcover Fiction',
        'hardcover-fiction',
        'Hardcover Fiction',
        [BookVO(
          'Amor Towles',
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          'THE LINCOLN HIGHWAY',
          null,
          null,
          null,
        )]),
    BooksListVO(
        'Combined Print and E-Book Fiction',
        'combined-print-and-e-book-fiction',
        'Combined Print & E-Book Fiction',
        [BookVO(
          'Amor Towles',
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          'THE LINCOLN HIGHWAY',
          null,
          null,
          null,
        )]),
  ];
}

List<BookVO> getEBooksMock() {
  return [
    BookVO(
      'Amor Towles',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'THE LINCOLN HIGHWAY',
      null,
      'flutter',
      'combined-print-and-e-book-fiction',
    ),
    BookVO(
      'Nicholas Sparks',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'THE WISH',
      null,
      'flutter',
      'combined-print-and-e-book-fiction',
    ),
    BookVO(
      'Anthony Doerr',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'CLOUD CUCKOO LAND',
      null,
      'flutter',
      'combined-print-and-e-book-fiction',
    ),
  ];
}

List<BookSearchResult> getBookSearchMock() {
  return [
    BookSearchResult(BookVO(
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'Beginning Flutter',
      null,
      'flutter',
      null,
    )),
    BookSearchResult(BookVO(
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'Pragmatic Flutter',
      null,
      'flutter',
      null,
    )),
    BookSearchResult(BookVO(
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      'Flutter For Dummies',
      null,
      'flutter',
      null,
    )),
  ];
}

List<ShelfVO> getShelfMock(){
  return [
    ShelfVO(uniqueID: 'test',name: 'ShelfName',bookList: getEBooksMock()),
    ShelfVO(uniqueID: 'update',name: 'ShelfName',bookList: getEBooksMock()),
  ];
}
